version: 0.2

env:
  variables:
    IMAGE_TAG: "v0.0.1" 
  parameter-store:
    DOCKERHUB_REGISTRY_USERNAME: /n9i-dark/docker-registry/username
    DOCKERHUB_REGISTRY_PASSWORD: /n9i-dark/docker-registry/password
    DOCKERHUB_REGISTRY_URL: /n9i-dark/docker-registry/url
    DOCKERHUB_REGISTRY_REPOSITORY: /n9i-dark/docker-registry/repository

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install -g @nestjs/cli  # Install NestJS CLI globally
      - cd n9i-dark-backend
      - npm install  # Install project dependencies

  pre_build:
    commands:
      - echo "Running tests..."
      # - npm run test   Run unit tests (adjust if your test script differs)
      - echo "Building NestJS app..."
      - npm run build  # Build the NestJS app (outputs to /dist)

  build:
    commands:
      - echo $DOCKERHUB_REGISTRY_PASSWORD
      - echo $DOCKERHUB_REGISTRY_USERNAME
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKERHUB_REGISTRY_PASSWORD" | docker login -u "$DOCKERHUB_REGISTRY_USERNAME"  --password-stdin "$DOCKERHUB_REGISTRY_URL"
      - echo "Building Docker image..."
      - docker build -t $DOCKERHUB_REGISTRY_USERNAME/$DOCKERHUB_REGISTRY_REPOSITORY:$IMAGE_TAG .
      - echo "Pushing Docker image to Docker Hub..."
      - docker push $DOCKERHUB_REGISTRY_USERNAME/$DOCKERHUB_REGISTRY_REPOSITORY:$IMAGE_TAG
  
  post_build:
    commands:
      - echo "Cleaning up..."
      - docker logout
      - echo "Successfully built and pushed $DOCKERHUB_REGISTRY_USERNAME/$DOCKERHUB_REGISTRY_REPOSITORY:$IMAGE_TAG"
      